spring:
  application:
    name: spring-docker
  r2dbc:
    url: r2dbc:mariadb://mariadb_database:3306/db_docker_test?serverTimezone=UTC&createDatabaseIfNotExist=true
    username: sreyes
    password: 54321
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
server:
  port: 9002