spring:
  application:
    name: spring-docker
  r2dbc:
    url: r2dbc:mariadb://localhost:${DB_PORT}/db_docker_test?serverTimezone=UTC&createDatabaseIfNotExist=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
server:
  port: 9002